# listens on loopback IPv4 and IPv6
bind 127.0.0.1 ::1 

# Specify the server verbosity level.
# This can be one of:
# debug (a lot of information, useful for development/testing)
# verbose (many rarely useful info, but not a mess like the debug level)
# notice (moderately verbose, what you want in production probably)
# warning (only very important / critical messages are logged)
# nothing (nothing is logged)
loglevel verbose

# Specify the timestamp format used in logs using 'log-timestamp-format'.
#
# - legacy: default format
# - iso8601: ISO 8601 extended date and time with time zone, on the form
#   yyyy-mm-ddThh:mm:ss.sss±hh:mm
# - milliseconds: milliseconds since the epoch
log-timestamp-format iso8601

always-show-logo yes

# Save the DB to disk.
#
# save <seconds> <changes> [<seconds> <changes> ...]
#
# The server will save the DB if the given number of seconds elapsed and it
# surpassed the given number of write operations against the DB.
#
# Snapshotting can be completely disabled with a single empty string argument
# as in following example:
#
# save ""
#
# Unless specified otherwise, by default the server will save the DB:
#   * After 3600 seconds (an hour) if at least 1 change was performed
#   * After 300 seconds (5 minutes) if at least 100 changes were performed
#   * After 60 seconds if at least 500 changes were performed
#
# You can set these explicitly by uncommenting the following line.
#
save 3600 1 300 100 60 500

